name = "BioRecordsProcessing"
uuid = "321bc2d7-9525-42af-8b23-17b2621d5ea8"
authors = ["Jonathan Bieler <jonathan.bieler@alumni.epfl.ch> and contributors"]
version = "0.2.3"

[deps]
BGZFStreams = "28d598bf-9b8f-59f1-b38c-5a06b4a0f5e6"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
XAM = "d759349c-bcba-11e9-07c2-5b90f8f05f7c"

[compat]
BGZFStreams = "0.3"
CodecZlib = "0.7"
Glob = "1.3"
julia = "1.7"
XAM = "0.3, 0.4"
GenomicFeatures = "2, 2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
